---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    app: jenkins
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
  name: traefik-ingress
  namespace: jenkins
spec:
  rules:
  - host: jenkinsapp.mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080
